-- ============================================================================
-- Comprehensive Supabase Migration - Combined from all migration files
-- ============================================================================
-- This migration file combines all migrations with idempotency checks.
-- It safely handles:
-- - Schemas (CREATE ... IF NOT EXISTS)
-- - Functions (CREATE OR REPLACE)
-- - Tables (CREATE TABLE IF NOT EXISTS)
-- - Indexes (CREATE INDEX IF NOT EXISTS)
-- - Policies (DROP IF EXISTS, then CREATE)
-- - Triggers (DROP TRIGGER IF EXISTS, then CREATE)
-- - Buckets (INSERT ... ON CONFLICT DO NOTHING)
-- ============================================================================

-- ============================================================================
-- 1. SCHEMA SETUP
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS "authenticative";

SET check_function_bodies = OFF;

-- ============================================================================
-- 2. FUNCTIONS
-- ============================================================================

-- Function to check if user is authenticated (MFA-aware)
CREATE OR REPLACE FUNCTION authenticative.is_user_authenticated()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT array[(select auth.jwt()->>'aal')] <@ (
    SELECT
      CASE
        WHEN count(id) > 0 THEN array['aal2']
        ELSE array['aal1', 'aal2']
      END as aal
    FROM auth.mfa_factors
    WHERE (auth.uid() = user_id)
    AND status = 'verified'
  );
$function$;

-- Function to handle new user creation (inserting into user_data)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_first_name text;
    v_last_name text;
BEGIN
    -- Extract first_name and last_name from raw_user_meta_data if available
    v_first_name := NEW.raw_user_meta_data->>'first_name';
    v_last_name := NEW.raw_user_meta_data->>'last_name';

    -- Insert the new user into user_data with default role 'user'
    INSERT INTO public.user_data (user_id, first_name, last_name, user_role)
    VALUES (NEW.id, v_first_name, v_last_name, 'user');

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    -- Log the error but don't fail the auth trigger
    RAISE WARNING 'Error in handle_new_user: %', SQLERRM;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;

-- ============================================================================
-- 3. STORAGE BUCKETS
-- ============================================================================

-- Insert storage buckets (idempotent with ON CONFLICT DO NOTHING)
INSERT INTO storage.buckets (id, name, public)
VALUES
  ('files', 'files', false),
  ('intake-audio', 'intake-audio', false),
  ('audio-text-audio', 'audio-text-audio', false)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 4. TABLES
-- ============================================================================

-- Table: todo_list
CREATE TABLE IF NOT EXISTS "public"."todo_list" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "urgent" boolean not null default false,
    "description" text,
    "done" boolean not null default false,
    "done_at" timestamp with time zone,
    "owner" uuid not null
);

-- Table: user_data
CREATE TABLE IF NOT EXISTS public.user_data (
    user_id uuid NOT NULL PRIMARY KEY,
    user_role text NOT NULL DEFAULT 'user',
    first_name text,
    last_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: intake_assessments
CREATE TABLE IF NOT EXISTS public.intake_assessments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    section_index integer NOT NULL,
    section_title text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: intake_responses
CREATE TABLE IF NOT EXISTS public.intake_responses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id uuid NOT NULL REFERENCES public.intake_assessments(id) ON DELETE CASCADE,
    question_number integer NOT NULL,
    question_text text NOT NULL,
    section_title text NOT NULL,
    audio_file_path text,
    duration_seconds integer,
    recorded_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: public_intake_assessments
CREATE TABLE IF NOT EXISTS public.public_intake_assessments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id text NOT NULL UNIQUE,
    email text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: public_intake_responses
CREATE TABLE IF NOT EXISTS public.public_intake_responses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id uuid NOT NULL REFERENCES public.public_intake_assessments(id) ON DELETE CASCADE,
    question_number integer NOT NULL,
    question_text text NOT NULL,
    section_title text NOT NULL,
    audio_file_path text,
    duration_seconds integer,
    recorded_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: audio_text_assessments
CREATE TABLE IF NOT EXISTS public.audio_text_assessments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    section_index integer NOT NULL,
    section_title text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Table: audio_text_responses
CREATE TABLE IF NOT EXISTS public.audio_text_responses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id uuid NOT NULL REFERENCES public.audio_text_assessments(id) ON DELETE CASCADE,
    question_number integer NOT NULL,
    question_text text NOT NULL,
    section_title text NOT NULL,
    transcript_text text,
    audio_file_path text,
    duration_seconds integer,
    recorded_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 5. TABLE CONSTRAINTS AND INDEXES (for tables without primary keys)
-- ============================================================================

-- Constraints for todo_list (only if constraint doesn't exist)
DO $$
BEGIN
    -- Create unique index if not exists
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'todo_list_pkey') THEN
        CREATE UNIQUE INDEX todo_list_pkey ON public.todo_list USING btree (id);
        ALTER TABLE "public"."todo_list" ADD CONSTRAINT "todo_list_pkey" PRIMARY KEY USING INDEX "todo_list_pkey";
    END IF;
    
    -- Add foreign key if not exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name = 'todo_list' AND constraint_name = 'todo_list_owner_fkey') THEN
        ALTER TABLE "public"."todo_list" ADD CONSTRAINT "todo_list_owner_fkey" FOREIGN KEY (owner) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
        ALTER TABLE "public"."todo_list" VALIDATE CONSTRAINT "todo_list_owner_fkey";
    END IF;
END $$;

-- Foreign key for user_data (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name = 'user_data' AND constraint_name = 'user_data_user_id_fkey') THEN
        ALTER TABLE public.user_data
        ADD CONSTRAINT user_data_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
        
        ALTER TABLE public.user_data
        VALIDATE CONSTRAINT user_data_user_id_fkey;
    END IF;
END $$;

-- ============================================================================
-- 6. ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE "public"."todo_list" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.public_intake_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.public_intake_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audio_text_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audio_text_responses ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 7. ROW LEVEL SECURITY POLICIES (with DROP IF EXISTS for idempotency)
-- ============================================================================

-- Policies for todo_list
DROP POLICY IF EXISTS "Owner can do everything" ON "public"."todo_list";
CREATE POLICY "Owner can do everything"
ON "public"."todo_list"
AS permissive
FOR ALL
TO authenticated
USING ((authenticative.is_user_authenticated() AND (owner = auth.uid())));

-- Policies for user_data
DROP POLICY IF EXISTS "Users can view own data" ON public.user_data;
CREATE POLICY "Users can view own data"
ON public.user_data
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own data" ON public.user_data;
CREATE POLICY "Users can update own data"
ON public.user_data
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role can manage all" ON public.user_data;
CREATE POLICY "Service role can manage all"
ON public.user_data
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for intake_assessments
DROP POLICY IF EXISTS "Users can view own assessments" ON public.intake_assessments;
CREATE POLICY "Users can view own assessments"
ON public.intake_assessments
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own assessments" ON public.intake_assessments;
CREATE POLICY "Users can insert own assessments"
ON public.intake_assessments
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own assessments" ON public.intake_assessments;
CREATE POLICY "Users can update own assessments"
ON public.intake_assessments
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role can manage all assessments" ON public.intake_assessments;
CREATE POLICY "Service role can manage all assessments"
ON public.intake_assessments
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for intake_responses
DROP POLICY IF EXISTS "Users can view own responses" ON public.intake_responses;
CREATE POLICY "Users can view own responses"
ON public.intake_responses
FOR SELECT
TO authenticated
USING (
    assessment_id IN (
        SELECT id FROM public.intake_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can insert own responses" ON public.intake_responses;
CREATE POLICY "Users can insert own responses"
ON public.intake_responses
FOR INSERT
TO authenticated
WITH CHECK (
    assessment_id IN (
        SELECT id FROM public.intake_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can update own responses" ON public.intake_responses;
CREATE POLICY "Users can update own responses"
ON public.intake_responses
FOR UPDATE
TO authenticated
USING (
    assessment_id IN (
        SELECT id FROM public.intake_assessments
        WHERE user_id = auth.uid()
    )
)
WITH CHECK (
    assessment_id IN (
        SELECT id FROM public.intake_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Service role can manage all responses" ON public.intake_responses;
CREATE POLICY "Service role can manage all responses"
ON public.intake_responses
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for public_intake_assessments
DROP POLICY IF EXISTS "Public assessments are readable by anyone" ON public.public_intake_assessments;
CREATE POLICY "Public assessments are readable by anyone"
ON public.public_intake_assessments
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Public assessments are insertable" ON public.public_intake_assessments;
CREATE POLICY "Public assessments are insertable"
ON public.public_intake_assessments
FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "Service role can manage all public assessments" ON public.public_intake_assessments;
CREATE POLICY "Service role can manage all public assessments"
ON public.public_intake_assessments
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for public_intake_responses
DROP POLICY IF EXISTS "Public responses are readable by anyone" ON public.public_intake_responses;
CREATE POLICY "Public responses are readable by anyone"
ON public.public_intake_responses
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Public responses are insertable" ON public.public_intake_responses;
CREATE POLICY "Public responses are insertable"
ON public.public_intake_responses
FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "Service role can manage all public responses" ON public.public_intake_responses;
CREATE POLICY "Service role can manage all public responses"
ON public.public_intake_responses
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for audio_text_assessments
DROP POLICY IF EXISTS "Users can view own assessments" ON public.audio_text_assessments;
CREATE POLICY "Users can view own assessments"
ON public.audio_text_assessments
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own assessments" ON public.audio_text_assessments;
CREATE POLICY "Users can insert own assessments"
ON public.audio_text_assessments
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own assessments" ON public.audio_text_assessments;
CREATE POLICY "Users can update own assessments"
ON public.audio_text_assessments
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role can manage all assessments" ON public.audio_text_assessments;
CREATE POLICY "Service role can manage all assessments"
ON public.audio_text_assessments
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policies for audio_text_responses
DROP POLICY IF EXISTS "Users can view own responses" ON public.audio_text_responses;
CREATE POLICY "Users can view own responses"
ON public.audio_text_responses
FOR SELECT
TO authenticated
USING (
    assessment_id IN (
        SELECT id FROM public.audio_text_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can insert own responses" ON public.audio_text_responses;
CREATE POLICY "Users can insert own responses"
ON public.audio_text_responses
FOR INSERT
TO authenticated
WITH CHECK (
    assessment_id IN (
        SELECT id FROM public.audio_text_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can update own responses" ON public.audio_text_responses;
CREATE POLICY "Users can update own responses"
ON public.audio_text_responses
FOR UPDATE
TO authenticated
USING (
    assessment_id IN (
        SELECT id FROM public.audio_text_assessments
        WHERE user_id = auth.uid()
    )
)
WITH CHECK (
    assessment_id IN (
        SELECT id FROM public.audio_text_assessments
        WHERE user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Service role can manage all responses" ON public.audio_text_responses;
CREATE POLICY "Service role can manage all responses"
ON public.audio_text_responses
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Storage Policies for 'files' bucket
DROP POLICY IF EXISTS "Give users access to own folder 1m0cqf_0" ON "storage"."objects";
CREATE POLICY "Give users access to own folder 1m0cqf_0"
ON "storage"."objects"
AS permissive
FOR DELETE
TO public
USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));

DROP POLICY IF EXISTS "Give users access to own folder 1m0cqf_1" ON "storage"."objects";
CREATE POLICY "Give users access to own folder 1m0cqf_1"
ON "storage"."objects"
AS permissive
FOR UPDATE
TO public
USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));

DROP POLICY IF EXISTS "Give users access to own folder 1m0cqf_2" ON "storage"."objects";
CREATE POLICY "Give users access to own folder 1m0cqf_2"
ON "storage"."objects"
AS permissive
FOR INSERT
TO public
WITH CHECK (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));

DROP POLICY IF EXISTS "Give users access to own folder 1m0cqf_3" ON "storage"."objects";
CREATE POLICY "Give users access to own folder 1m0cqf_3"
ON "storage"."objects"
AS permissive
FOR SELECT
TO public
USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));

-- Storage Policies for 'intake-audio' bucket
DROP POLICY IF EXISTS "Authenticated users can upload to intake-audio" ON storage.objects;
CREATE POLICY "Authenticated users can upload to intake-audio"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'intake-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Authenticated users can read own intake-audio files" ON storage.objects;
CREATE POLICY "Authenticated users can read own intake-audio files"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'intake-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Authenticated users can delete own intake-audio files" ON storage.objects;
CREATE POLICY "Authenticated users can delete own intake-audio files"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'intake-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Storage Policies for 'audio-text-audio' bucket
DROP POLICY IF EXISTS "Authenticated users can upload to audio-text-audio" ON storage.objects;
CREATE POLICY "Authenticated users can upload to audio-text-audio"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'audio-text-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Authenticated users can read own audio-text-audio files" ON storage.objects;
CREATE POLICY "Authenticated users can read own audio-text-audio files"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'audio-text-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Authenticated users can delete own audio-text-audio files" ON storage.objects;
CREATE POLICY "Authenticated users can delete own audio-text-audio files"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'audio-text-audio' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Service role policies for storage
DROP POLICY IF EXISTS "Service role can manage intake-audio" ON storage.objects;
CREATE POLICY "Service role can manage intake-audio"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'intake-audio');

DROP POLICY IF EXISTS "Service role can manage audio-text-audio" ON storage.objects;
CREATE POLICY "Service role can manage audio-text-audio"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'audio-text-audio');

-- ============================================================================
-- 8. GRANT PERMISSIONS TO ROLES
-- ============================================================================

-- Permissions for todo_list
GRANT DELETE ON TABLE "public"."todo_list" TO "anon";
GRANT INSERT ON TABLE "public"."todo_list" TO "anon";
GRANT REFERENCES ON TABLE "public"."todo_list" TO "anon";
GRANT SELECT ON TABLE "public"."todo_list" TO "anon";
GRANT TRIGGER ON TABLE "public"."todo_list" TO "anon";
GRANT TRUNCATE ON TABLE "public"."todo_list" TO "anon";
GRANT UPDATE ON TABLE "public"."todo_list" TO "anon";

GRANT DELETE ON TABLE "public"."todo_list" TO "authenticated";
GRANT INSERT ON TABLE "public"."todo_list" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."todo_list" TO "authenticated";
GRANT SELECT ON TABLE "public"."todo_list" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."todo_list" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."todo_list" TO "authenticated";
GRANT UPDATE ON TABLE "public"."todo_list" TO "authenticated";

GRANT DELETE ON TABLE "public"."todo_list" TO "service_role";
GRANT INSERT ON TABLE "public"."todo_list" TO "service_role";
GRANT REFERENCES ON TABLE "public"."todo_list" TO "service_role";
GRANT SELECT ON TABLE "public"."todo_list" TO "service_role";
GRANT TRIGGER ON TABLE "public"."todo_list" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."todo_list" TO "service_role";
GRANT UPDATE ON TABLE "public"."todo_list" TO "service_role";

-- Permissions for user_data
GRANT SELECT ON public.user_data TO authenticated;
GRANT UPDATE ON public.user_data TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_data TO service_role;

-- Permissions for intake_assessments and intake_responses
GRANT SELECT, INSERT, UPDATE ON public.intake_assessments TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.intake_responses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.intake_assessments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.intake_responses TO service_role;

-- Permissions for public_intake_assessments and public_intake_responses
GRANT INSERT, SELECT ON public.public_intake_assessments TO anon;
GRANT INSERT, SELECT ON public.public_intake_responses TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.public_intake_assessments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.public_intake_responses TO service_role;

-- Permissions for audio_text_assessments and audio_text_responses
GRANT SELECT, INSERT, UPDATE ON public.audio_text_assessments TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.audio_text_responses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audio_text_assessments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audio_text_responses TO service_role;

-- ============================================================================
-- 9. TRIGGERS (with DROP IF EXISTS for idempotency)
-- ============================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 10. INDEXES (CREATE IF NOT EXISTS)
-- ============================================================================

-- Indexes for todo_list
CREATE INDEX IF NOT EXISTS idx_todo_list_owner ON public.todo_list(owner);
CREATE INDEX IF NOT EXISTS idx_todo_list_done ON public.todo_list(done);

-- Indexes for user_data
CREATE INDEX IF NOT EXISTS idx_user_data_created_at ON public.user_data(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_data_user_role ON public.user_data(user_role);

-- Indexes for intake_assessments
CREATE INDEX IF NOT EXISTS idx_intake_assessments_user_id ON public.intake_assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_intake_assessments_created_at ON public.intake_assessments(created_at DESC);

-- Indexes for intake_responses
CREATE INDEX IF NOT EXISTS idx_intake_responses_assessment_id ON public.intake_responses(assessment_id);
CREATE INDEX IF NOT EXISTS idx_intake_responses_created_at ON public.intake_responses(created_at DESC);

-- Indexes for public_intake_assessments
CREATE INDEX IF NOT EXISTS idx_public_intake_assessments_session_id ON public.public_intake_assessments(session_id);
CREATE INDEX IF NOT EXISTS idx_public_intake_assessments_created_at ON public.public_intake_assessments(created_at DESC);

-- Indexes for public_intake_responses
CREATE INDEX IF NOT EXISTS idx_public_intake_responses_assessment_id ON public.public_intake_responses(assessment_id);
CREATE INDEX IF NOT EXISTS idx_public_intake_responses_created_at ON public.public_intake_responses(created_at DESC);

-- Indexes for audio_text_assessments
CREATE INDEX IF NOT EXISTS idx_audio_text_assessments_user_id ON public.audio_text_assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_audio_text_assessments_created_at ON public.audio_text_assessments(created_at DESC);

-- Indexes for audio_text_responses
CREATE INDEX IF NOT EXISTS idx_audio_text_responses_assessment_id ON public.audio_text_responses(assessment_id);
CREATE INDEX IF NOT EXISTS idx_audio_text_responses_created_at ON public.audio_text_responses(created_at DESC);

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- All tables, functions, triggers, policies, and indexes have been created
-- or verified with idempotency checks. Safe to re-run without errors.
-- ============================================================================
